/*CREATE TABLE HEXSPACE (ID VARCHAR(20), COLOR VARCHAR(20), STRENGTH INT);
CREATE TABLE TILE (ID CHAR, HEXSPACE ARRAY);
CREATE TABLE STRIP (ID CHAR, HEXSPACE ARRAY);
CREATE TABLE BOARD (BOARDID INT,TILES ARRAY,TILESROTATION ARRAY,TILESPOSITIONX ARRAY, TILESPOSITIONY ARRAY,
                            STRIP ARRAY,STRIPROTATION ARRAY,STRIPPOSITIONX ARRAY,STRIPPOSITIONY ARRAY,
                            BLOCKADE ARRAY,STARTINGSPACES ARRAY,ENDINGSPACES ARRAY,ENDINGSPACEPOSITION ARRAY);
CREATE TABLE BLOCKADE (ID VARCHAR(20), COLOR VARCHAR(20), STRENGTH INT, BLOCKADEID INT);*/
